#!/bin/bash

echo "Content-type: text/plain"
echo ""

# GPIO 17 pin 11 comanda relè alimentazione
# GPIO 24 pin 16 comanda relè in2 collegato al sinistro (lungo)
# GPIO 27 pin 13 comanda relè in1 collegato al destro

# Imposta il volume al 100%
#sudo amixer -c 0 sset "Master" 100%

# Imposta la modalità GPIO (BCM)
gpio -g mode 27 out
gpio -g mode 24 out
gpio -g mode 17 out

# Imposta il pin GPIO27 a livello basso
gpio -g write 17 0
gpio -g write 27 0
gpio -g write 24 0

# Avvio della riproduzione audio in loop in background e salva il PID
nohup bash -c 'while true; do
    sudo aplay -D hw:0,0 -v -r 192000 /home/pi/Suono_Multiplo/Rampa.wav
    sleep 1s
done' > /dev/null 2>&1 &

echo "PID: $!"
echo "Emissione Audio Avviata"
